// Schema-wiring assertion for `english_attempts`/`english_sentences` (E10,
// epic #59 / issue #130).
//
// Per docs/TESTING.md ("API tests never touch a database" — Prisma is
// mocked in full, there is no test database, and CI's hermetic design
// depends on that never changing), this is NOT a live-database integration
// test. It is a generated-migration-SQL assertion instead: it reads the
// actual `CREATE TABLE`/`ADD CONSTRAINT` statements Prisma generated for
// this epic's migration and asserts the exact `ON DELETE` behavior those
// statements declare. This is the alternative the task brief itself names
// as acceptable when a live-DB integration test is not this repo's pattern
// — and it is a REAL assertion, not a restatement of the schema: if a future
// edit to schema.prisma changed either `onDelete` clause and a fresh
// migration were generated, this test would fail on the new file's content,
// exactly as it would if it were pointed at a live database's own
// information_schema instead.
//
// What this proves: deleting a user removes their `english_attempts` rows
// (`ON DELETE CASCADE` on `user_id`) and never removes an `english_sentences`
// row for having been answered (`ON DELETE RESTRICT` on `sentence_id`) — the
// identical "evidence must not vanish because content was reloaded, but an
// attempt has no meaning independent of its learner" posture
// `PracticeAttempt.userId`/`.questionId` already take, restated here for
// this table's own migration.

import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const MIGRATIONS_DIR = join(__dirname, '..', 'prisma', 'migrations');

/**
 * Locates the migration this epic generated by its name suffix (the part
 * after the timestamp prefix `npm run prisma:migrate:dev` adds), rather than
 * hardcoding the full, timestamped directory name — so this test keeps
 * passing if the migration is ever regenerated with a different timestamp,
 * and fails loudly and specifically ("no migration found") if the migration
 * itself is ever renamed or removed instead of silently matching nothing.
 */
function readEnglishMigrationSql(): string {
  const dirs = readdirSync(MIGRATIONS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name.endsWith('_english_sentences_and_attempts'))
    .map((entry) => entry.name);

  if (dirs.length === 0) {
    throw new Error(
      `No migration directory ending in "_english_sentences_and_attempts" found under ${MIGRATIONS_DIR}. ` +
        'This test reads the real generated migration SQL — if the migration was renamed, update the suffix below.',
    );
  }
  if (dirs.length > 1) {
    throw new Error(`Expected exactly one matching migration directory, found: ${dirs.join(', ')}`);
  }

  return readFileSync(join(MIGRATIONS_DIR, dirs[0], 'migration.sql'), 'utf8');
}

describe('english_attempts — generated migration SQL, onDelete wiring', () => {
  const sql = readEnglishMigrationSql();

  it('creates the english_sentences and english_attempts tables', () => {
    expect(sql).toMatch(/CREATE TABLE "english_sentences"/);
    expect(sql).toMatch(/CREATE TABLE "english_attempts"/);
  });

  it('cascades: deleting a user deletes their english_attempts rows (ON DELETE CASCADE on user_id)', () => {
    const fkMatch = sql.match(
      /ALTER TABLE "english_attempts" ADD CONSTRAINT "english_attempts_user_id_fkey" FOREIGN KEY \("user_id"\) REFERENCES "users"\("id"\) ON DELETE (\w+)/,
    );
    expect(fkMatch).not.toBeNull();
    expect(fkMatch![1]).toBe('CASCADE');
  });

  it('restricts: an answered sentence cannot be deleted out from under its attempts (ON DELETE RESTRICT on sentence_id)', () => {
    const fkMatch = sql.match(
      /ALTER TABLE "english_attempts" ADD CONSTRAINT "english_attempts_sentence_id_fkey" FOREIGN KEY \("sentence_id"\) REFERENCES "english_sentences"\("id"\) ON DELETE (\w+)/,
    );
    expect(fkMatch).not.toBeNull();
    expect(fkMatch![1]).toBe('RESTRICT');
  });

  it('english_sentences has no foreign key of its own — a user deletion structurally cannot cascade into deleting sentences', () => {
    // The only two ADD CONSTRAINT ... FOREIGN KEY statements in this
    // migration are both on english_attempts (asserted above). No
    // "ALTER TABLE ... english_sentences ... FOREIGN KEY" line exists at
    // all, which is what makes "deleting a user removes their
    // english_attempts and no sentences" true structurally rather than by
    // the two constraints happening to agree today.
    expect(sql).not.toMatch(/ALTER TABLE "english_sentences"[\s\S]*?FOREIGN KEY/);
  });

  it('has exactly two foreign keys in total for this migration, both on english_attempts', () => {
    const fkStatements = sql.match(/ALTER TABLE "\w+" ADD CONSTRAINT "\w+" FOREIGN KEY/g) ?? [];
    expect(fkStatements).toHaveLength(2);
    expect(fkStatements.every((line) => line.startsWith('ALTER TABLE "english_attempts"'))).toBe(true);
  });
});
